### ISSUE TITLE
No need to check Wire.available().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_VCNL4010#1]
Four times the "while(!Wire.available());" is used. That is not needed. When Wire.requestFrom() has returned the I2C transmission has ended and the data is in the buffer.
I assume that TinyWire works the same.

**Comment by tdicola** [comment]
Thanks for raising the issue!  I'm a little hesitant to change the code because it's working as-is and the Arduino API docs mention that available() should be checked after calling requestFrom(): https://www.arduino.cc/en/Reference/WireAvailable  It might be true that requestFrom has all the data on AVR and other platforms, but it could be problematic if a new platform comes along and is implemented strictly according to the docs / 'spec'.

**Comment by Koepel** [comment]
The Wire.available() returns the number of received bytes (in the receive-buffer inside the Wire library). It should not be used to wait. Whenever it is used it "should" be called after Wire.requestFrom() and in the onReceive() handler, because that is the only situation that there is data in the receive-buffer.
Since the Wire.requestFrom() returns the number of bytes and the 'howMany' parameter also has the number of bytes, the Wire.available() is just an extra function to check the number of bytes in the receive-buffer.

Using a 'while' might cause the code to stop. For example when a I2C collisions did happen and the number of received bytes is zero.

Please confirm this with the Arduino team and share it with the Adafruit team. You read the reference as if it must be called, but that is not so, and using the 'while' is (a little) wrong.
Using the Wire library strictly is by not using the while-statement. Read the rest of the Wire API reference.
Maybe in the future there will be I2C functions that do not wait until the I2C transmission has finished. But waiting for Wire.available() like that will still be wrong.

I have written many of these issues, because I want to contribute to Adafruit to make better and cleaner code, because many others copy that code.
